import type { EmotionRegistry } from "../types/emotions";

export const emotionRegistry: EmotionRegistry = {
  neutral: {
    id: "neutral",
    label: "Neutral",
    defaultDuration: 0,
    variants: {
      head: { rotate: 0, y: 0 },
      eyes: { scaleY: 1 },
      mouth: { scaleX: 1, scaleY: 1 },
      armLeft: { rotate: 0 },
      armRight: { rotate: 0 },
      tail: { rotate: 0 },
    },
  },
  happy: {
    id: "happy",
    label: "Feliz",
    defaultDuration: 4000,
    variants: {
      head: { rotate: 3, y: -2 },
      eyes: { scaleY: 0.85 },
      mouth: { scaleX: 1.2, scaleY: 1.1 },
      armLeft: { rotate: -15 },
      armRight: { rotate: 15 },
      tail: { rotate: 18 },
    },
    transition: { type: "spring", stiffness: 300, damping: 20 },
  },
  excited: {
    id: "excited",
    label: "Emocionado",
    defaultDuration: 3000,
    variants: {
      root: { y: [0, -6, 0] },
      head: { rotate: [-2, 2, -2] },
      eyes: { scaleY: 1.1 },
      mouth: { scaleX: 1.3, scaleY: 1.2 },
      armLeft: { rotate: [-25, -10, -25] },
      armRight: { rotate: [25, 10, 25] },
      tail: { rotate: [15, -15, 15] },
    },
    transition: { duration: 0.6, repeat: Infinity, repeatType: "reverse" },
  },
  curious: {
    id: "curious",
    label: "Curioso",
    defaultDuration: 5000,
    variants: {
      head: { rotate: 8, x: 3 },
      eyes: { scaleX: 1.1 },
      mouth: { scaleX: 0.9 },
      armLeft: { rotate: -5 },
      tail: { rotate: 8 },
    },
    transition: { type: "spring", stiffness: 200, damping: 25 },
  },
  thinking: {
    id: "thinking",
    label: "Pensando",
    defaultDuration: 0,
    variants: {
      head: { rotate: -5, y: 2 },
      eyes: { y: -1 },
      mouth: { scaleX: 0.7 },
      armLeft: { rotate: -30, y: -5 },
      armRight: { rotate: 20 },
    },
    transition: { duration: 0.5 },
  },
  surprised: {
    id: "surprised",
    label: "Sorprendido",
    defaultDuration: 2500,
    variants: {
      head: { y: -4, scale: 1.05 },
      eyes: { scaleX: 1.3, scaleY: 1.3 },
      mouth: { scaleX: 0.6, scaleY: 1.4 },
      armLeft: { rotate: -40 },
      armRight: { rotate: 40 },
      tail: { rotate: -20 },
    },
    transition: { type: "spring", stiffness: 400, damping: 15 },
  },
  sad: {
    id: "sad",
    label: "Triste",
    defaultDuration: 4000,
    variants: {
      head: { rotate: -3, y: 3 },
      eyes: { scaleY: 0.9, y: 1 },
      mouth: { scaleX: 0.8, scaleY: 0.6, y: 2 },
      armLeft: { rotate: 5 },
      armRight: { rotate: -5 },
      tail: { rotate: -8 },
    },
    transition: { duration: 0.6 },
  },
};
